export interface AccountEnv {
  DB: D1Database;
  LICENSE_SIGNING_PRIVATE_KEY: string;
  PADDLE_WEBHOOK_SECRET: string;
  GITHUB_OAUTH_CLIENT_ID: string;
  GITHUB_OAUTH_CLIENT_SECRET: string;
  AUTH_SECRET: string;
  PADDLE_API_KEY: string;
  LICENSE_PUBLIC_KEY: string;
  TELEGRAM_BOT_TOKEN: string;
  TELEGRAM_BOT_USERNAME: string;
  TELEGRAM_WEBHOOK_SECRET: string;
}
